# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WiscSIMSTool3
                                 A QGIS plugin
 useful tools for WiscSIMS sessions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-12-26
        copyright            : (C) 2019 by WiscSIMS
        email                : kitajima@wisc.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WiscSIMSTool3 class from file WiscSIMSTool3.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .wiscsims_tool3 import WiscSIMSTool3
    return WiscSIMSTool3(iface)
